package view;

/*
 * Projet:      Bibliotheque - module 120
 * Fichier:     AjoutEmpruntExemplaireDialog.java
 * Auteur:      Damien Papaux
 * Description: 
 */

import business.Bibliotheque;
import business.Exemplaire;
import business.Livre;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/*
 * Projet:      Bibliotheque - module 120
 * Fichier:     AjoutLivreDialog.java
 * Auteur:      LBI
 * Description: 
 */

public class AjoutLivreDialog extends javax.swing.JDialog {

    /**
     * Creates new form AjoutLivreDialog
     */
    public AjoutLivreDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setSize(600, 480);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitre = new javax.swing.JLabel();
        txtTitre = new javax.swing.JTextField();
        txtEditeur = new javax.swing.JTextField();
        lblEditeur = new javax.swing.JLabel();
        lblGenre = new javax.swing.JLabel();
        cbGenre = new javax.swing.JComboBox();
        lblEvaluation = new javax.swing.JLabel();
        spNombreExemplaires = new javax.swing.JSpinner();
        lblNbExemplaires = new javax.swing.JLabel();
        btnAjouter = new javax.swing.JButton();
        btnEffacer = new javax.swing.JButton();
        cbEvaluation = new javax.swing.JComboBox();
        lblAuteur = new javax.swing.JLabel();
        txtAuteur = new javax.swing.JTextField();
        btnRetour = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nouveau livre");

        lblTitre.setText("Titre *");

        lblEditeur.setText("Editeur");

        lblGenre.setText("Genre *");

        cbGenre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Science-Fiction", "Policier", "Littérature", "Littérature pour enfants", " " }));

        lblEvaluation.setText("Evaluation");

        spNombreExemplaires.setValue(1);

        lblNbExemplaires.setText("Nombre d'exemplaires");

        btnAjouter.setMnemonic('A');
        btnAjouter.setText("Ajouter");
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        btnEffacer.setMnemonic('E');
        btnEffacer.setText("Effacer");
        btnEffacer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacerActionPerformed(evt);
            }
        });

        cbEvaluation.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "*", "**", "***", "****" }));

        lblAuteur.setText("Auteur");

        btnRetour.setMnemonic('R');
        btnRetour.setText("Retour");
        btnRetour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetourActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNbExemplaires)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spNombreExemplaires, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEditeur)
                            .addComponent(lblTitre)
                            .addComponent(lblGenre)
                            .addComponent(lblAuteur))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEditeur)
                            .addComponent(txtAuteur)
                            .addComponent(txtTitre, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbGenre, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEvaluation)
                        .addGap(26, 26, 26)
                        .addComponent(cbEvaluation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAjouter)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEffacer)
                        .addGap(18, 18, 18)
                        .addComponent(btnRetour)))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTitre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuteur)
                    .addComponent(txtAuteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEditeur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEditeur))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGenre)
                    .addComponent(cbGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEvaluation)
                    .addComponent(cbEvaluation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNbExemplaires)
                    .addComponent(spNombreExemplaires, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 186, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAjouter)
                    .addComponent(btnEffacer)
                    .addComponent(btnRetour))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        // Récupération des valeurs saisies
        String titre = txtTitre.getText();
        String editeur = txtEditeur.getText();
        String auteur = txtAuteur.getText();
        String genre = (String) cbGenre.getSelectedItem();
        String evaluation = (String) cbEvaluation.getSelectedItem();
        int nbExemplaires = (int) spNombreExemplaires.getValue();
        
        // On contrôle que le titre ne soit pas vide
        if (titre.isEmpty()) {
            txtTitre.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Veuillez corriger les champs en rouge");
        }
        else if (nbExemplaires <= 0) {
                txtTitre.setBackground(Color.red);
                JOptionPane.showMessageDialog(this, "Le nombre d'exemplaires doit être supérieur à 0");
        }
        else {
            // Création du livre
            Livre livre = new Livre(titre,auteur, editeur,genre,evaluation,"");
            
            // Création des exemplaires
            String numeros = "";
            for ( int i=0; i<nbExemplaires; i++) {
                // Création de l'exemplaire, le numéro est généré dans le constructeur
                Exemplaire exemplaire = new Exemplaire(livre);
                numeros = numeros + " " + exemplaire.getNoExemplaire();
                
                // Ajout dans la liste
                Bibliotheque biblio = Bibliotheque.getInstance();
                biblio.getListeExemplaires().put(exemplaire.getNoExemplaire(), exemplaire);
            }
            JOptionPane.showMessageDialog(this, "Les exemplaires" + numeros + " ont été créés.");
            btnAjouter.setEnabled(false);
        }
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnRetourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetourActionPerformed
        dispose();
    }//GEN-LAST:event_btnRetourActionPerformed

    private void btnEffacerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEffacerActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnEffacer;
    private javax.swing.JButton btnRetour;
    private javax.swing.JComboBox cbEvaluation;
    private javax.swing.JComboBox cbGenre;
    private javax.swing.JLabel lblAuteur;
    private javax.swing.JLabel lblEditeur;
    private javax.swing.JLabel lblEvaluation;
    private javax.swing.JLabel lblGenre;
    private javax.swing.JLabel lblNbExemplaires;
    private javax.swing.JLabel lblTitre;
    private javax.swing.JSpinner spNombreExemplaires;
    private javax.swing.JTextField txtAuteur;
    private javax.swing.JTextField txtEditeur;
    private javax.swing.JTextField txtTitre;
    // End of variables declaration//GEN-END:variables
}
