package view;

/*
 * Projet:      Bibliotheque - module 120
 * Fichier:     AjoutEmpruntExemplaireDialog.java
 * Auteur:      Damien Papaux
 * Description: 
 */
import business.Bibliotheque;
import business.Client;
import business.Emprunt;
import business.Exemplaire;
import java.awt.Color;
import java.time.LocalDate;
import javax.swing.JOptionPane;

public class AjoutEmpruntExemplaireDialog extends javax.swing.JDialog {

    /**
     * Creates new form AjoutEmprunt
     */
    public AjoutEmpruntExemplaireDialog(java.awt.Frame parent, boolean modal, Client c) {
        super(parent, modal);
        initComponents();
        this.setSize(600, 480);
        this.setResizable(false);

        // On stocke le client afin de lui associer l'exemplaire
        this.client = c;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNoExemplaire = new javax.swing.JLabel();
        txtNoExemplaire = new javax.swing.JTextField();
        btnRechercher = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtExemplaire = new javax.swing.JTextArea();
        btnEmprunter = new javax.swing.JButton();
        btnAnnuler = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nouvel emprunt");

        lblNoExemplaire.setText("No exemplaire");

        btnRechercher.setText("Rechercher");
        btnRechercher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercherActionPerformed(evt);
            }
        });

        txtExemplaire.setColumns(20);
        txtExemplaire.setRows(5);
        jScrollPane1.setViewportView(txtExemplaire);

        btnEmprunter.setMnemonic('C');
        btnEmprunter.setText("Confirmer l'emprunt");
        btnEmprunter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmprunterActionPerformed(evt);
            }
        });

        btnAnnuler.setMnemonic('R');
        btnAnnuler.setText("Retour");
        btnAnnuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnulerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEmprunter)
                        .addGap(18, 18, 18)
                        .addComponent(btnAnnuler))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNoExemplaire)
                        .addGap(18, 18, 18)
                        .addComponent(txtNoExemplaire, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnRechercher))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNoExemplaire)
                    .addComponent(txtNoExemplaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRechercher))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 215, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEmprunter)
                    .addComponent(btnAnnuler))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRechercherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercherActionPerformed

        // On définit un motif pour un nombre
        String motif = "^[0-9]{1,}$";

        // Récupérer le numéro de client saisi
        String noExemplaire = txtNoExemplaire.getText();

        if (!noExemplaire.matches(motif)) {
            txtNoExemplaire.setBackground(Color.red);
            JOptionPane.showMessageDialog(this, "Veuillez corriger le numéro d'exemplaire.");
        } else {
            // On recherche l'exemplaire
            Bibliotheque biblio = Bibliotheque.getInstance();
            exemplaire = biblio.rechercherExemplaire(Integer.parseInt(noExemplaire));
            
            if (exemplaire != null) {
               // On affiche les données
               txtExemplaire.setText(exemplaire.getLivre().getTitre() + '\n'
                                     + exemplaire.getLivre().getAuteur());
            }
        }
    }//GEN-LAST:event_btnRechercherActionPerformed

    private void btnAnnulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnulerActionPerformed
        dispose();
    }//GEN-LAST:event_btnAnnulerActionPerformed

    private void btnEmprunterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmprunterActionPerformed
        // On teste si un exemplaire existe
        if (exemplaire != null) {
            
            // On créée et stocke l'emprunt
            Emprunt e = new Emprunt(LocalDate.now(), null, exemplaire);
            client.ajouterEmprunt(new Emprunt(LocalDate.now(), LocalDate.MIN, exemplaire));
            
            JOptionPane.showMessageDialog(this, "L'emprunt a été enregistré.");
        } else {
            JOptionPane.showMessageDialog(this, "Cet exemplaire n'existe pas.");
        }
    }//GEN-LAST:event_btnEmprunterActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnuler;
    private javax.swing.JButton btnEmprunter;
    private javax.swing.JButton btnRechercher;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNoExemplaire;
    private javax.swing.JTextArea txtExemplaire;
    private javax.swing.JTextField txtNoExemplaire;
    // End of variables declaration//GEN-END:variables
    private Client client;
    private Exemplaire exemplaire;
}
